import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Abdelrahman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          padding: "20px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          borderBottom: "#333 solid 1px",
          color: "black"
        }}>
          <Link href="/">home</Link>
          <Link href="/dashboard">dashboard</Link>
          <Link href="/ProductList">ProductList</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
